### ISSUE TITLE
Parse tree compiler 😮

### ISSUE THREAD

**Issue by StoneCypher** [StoneCypher/jssm#251]
* [x] Rule parsing basis #255
* [x] Rule selectors #256 
* [x] Throw on not known rule #257 
* [x] From/to chains to arrays #258
