### ISSUE TITLE
Todo

### ISSUE THREAD

**Issue by StoneCypher** [StoneCypher/jssm#266]
* [ ] Start preparing the FSL transition
* [ ] Factories
* [ ] Allow randomness by removing single action name origin on rules w/ probabilities
* [ ] Moar Direktiv
  * [x] `machine_author`
  * [x] `machine_license`
  * [x] `machine_repository`
  * [ ] `npm_name`
* [ ] Islands
  * [ ] Detect
  * [ ] Explicitly disallow
* [ ] Compiler support #277
  * [ ] Arrow decorations
  * [x] Node statements
  * [ ] edgeURL
  * [ ] edgeTooltip
  * [ ] Control ports for self-reference to get elegant loops
  * [ ] Measured probability alters render edge weight
* [ ] Multi-name syntax for actions (thanks ljharb)
  * probably `solid { actions: [melt heat]; } -> liquid;` or thereabouts
* [ ] Sensors
  * Sensors are a block of functions that the state machine's handlers can use to call out by name to find out about the world, without keeping that information as internal state
    * By example, a vending machine DSL will need sensors for whether it has cans remaining, and nickels remaining
    * By example, a ghost DSL in a pac-man machine will need sensors for whether they're at a junction, and whether pacman is enraged
  * [ ] Provide sensor in data notation
  * [ ] Provide sensor in DSL
  * [ ] Change existing sensor
  * [ ] Remove sensor
* [ ] Highlighter fragments
  * [x] [Sublime Text](https://github.com/StoneCypher/sublime-jssm)
    * [x] [Package Control](https://github.com/wbond/package_control_channel/pull/6526)
    * [ ] [Github Linguist](https://github.com/github/linguist/blob/master/grammars.yml)
  * [ ] [Atom](https://discuss.atom.io/t/convert-sublime-grammar-to-atom-grammar/14843)
  * [ ] Vim
  * [ ] Emacs
  * [x] [Ace](https://github.com/ajaxorg/ace/pull/3389)
  * [ ] [CodeMirror](http://codemirror.net/doc/manual.html#modeapi) and [repo](https://github.com/codemirror/CodeMirror/tree/master/mode)
    * [ ] [Brackets](https://github.com/adobe/brackets/wiki/Language-Support#defining-a-new-language)
  * [ ] [Visual Studio Code](https://stackoverflow.com/questions/30687783/create-custom-language-in-visual-studio-code)
* [ ] State Labels
  * [ ] Definable in PEG
    * [ ] Disableable in per-render config
  * [ ] Compiled
  * [ ] Shown in graph
  * [ ] Used in error messages and exceptions
* [ ] State Groups
  * [x] Anonymously definable in PEG
  * [x] Nameable in PEG
  * [ ] Referenceable in PEG
  * [x] Part of PEG primitives
  * [ ] Usable in compiler
* [ ] Graph inputs and outputs
  * Do we need these?  Signals and setting data seem to preclude inputs, and outputs can just be reading data, no?
* [ ] Start and End Nodes
  * [ ] Start nodes
    * [x] Can specify in PEG #264
    * [x] Goes through compiler #279
    * [ ] Can specify which to start from in constructor config
    * [x] Uses first in list as default #278
    * [ ] No repetitions
    * [ ] Enforce that all states actually exist
  * [x] End nodes #281
* [ ] Probabilistics
  * [ ] Measure transition follows over time, to calculate probabilities
  * [ ] Measure state reaches over time, to calculate probabilities
  * [ ] Measure state reaches from X over time, to calculate probabilities
  * [ ] correct support for probability `0`, probability `false` in random state transitions, tests
* [ ] The Ending of Machines
  * [ ] `is_ended`
  * [ ] auto-`ending` at a `final` node
  * [ ] `can_end`
  * [ ] forced ending
  * [ ] refusing further actions/transitions/etc because ended
  * [ ] ties to end nodes
  * [ ] un-ending
* [ ] Much improved `README`
  * [ ] Better content
    * [x] TL;DR
    * [x] Quick Start
    * [x] DSL Start
    * [ ] Datastructure start
    * [x] What is a state machine, and why
    * [ ] Examples section
    * [ ] Comparisons to other FSM libs
  * [ ] `README` to site
    * [ ] H1s become pages
    * [ ] TL;DR at top becomes site main page
    * [ ] consider cloudfront in front of gh pages (or switching to s3)
    * [ ] Find a theming mechanism
* [ ] Color theme generator
* [ ] Add labels as `arc_label` to edges
* [ ] Stricter machine configs
  * [ ] min/max `jssm` version for machine
  * [ ] name list for hook provision
  * [ ] name list for validator provision
  * [ ] check all configs and make sure each has an enforce
* [ ] Node display types and characteristics
  * [ ] Start node 
  * [ ] End node
  * [ ] Terminal node
  * [ ] General node
  * [ ] Member-of-group node
* [ ] Data issues
  * [ ] Real support for added data
  * [ ] Data is transactional on all hooks
  * [ ] Data is validatable on all hooks
  * [ ] How do we support prev/next state in hooks?  `.nextData` ?
  * [ ] Should validators be allowed to modify data?
  * [ ] Should notifiers be allowed to modify data?
* [ ] Remaining badge work
  * [ ] Move badge targets to reports, instead of their images [bug!]
  * [ ] [codecov.io](https://codecov.io/gh/babel/babel/pull/5717?src=pr&el=h1)
  * [ ] [greenkeeper 2](https://greenkeeper.io/)
  * [x] remove failing `builds since`
* [ ] Machine state extraction and history
  * [ ] Jump backwards or forwards in machine state history feature
  * [ ] Keep a machine state history feature
  * [ ] Validate a saved machine state core feature
    * [ ] Can data be practically validated?
  * [ ] Load a complete machine state (incl definition) core feature
    * [ ] Discard history should be default, but keep history should be opt-in-able
  * [ ] Store a complete machine state (incl definition) core feature
    * [ ] Discard history should be default, but keep history should be opt-in-able
* [ ] Auto-api
  * [ ] Auto for actions
    * [ ] enable, default off
    * [ ] prefix, default `do`
  * [ ] Auto for transitions
    * [ ] enable, default off
    * [ ] prefix, default `to`
  * [ ] Auto for forced transitions
    * [ ] enable, default off
    * [ ] prefix, default `force`
* [ ] ES5 Feature Support
  * [ ] Events as hooks instead of just callbacks
* [ ] ES6 Feature Support
  * Various state machines claim things like `Promise` support.  It's not immediately clear how or why this matters.  Research is warranted.
  * Look into
    * [ ] `Promise` support
    * [ ] Generator support
    * [ ] `async await` support
    * [ ] `Observable` support
* [ ] Hooks
  * [ ] Notification hooks
    * Notification hooks tell the outside after something has happened
    * [ ] Entering
    * [ ] Exiting
    * [ ] Any transition
    * [ ] Forced transition
    * [ ] Data change
    * [ ] Any action
  * [ ] Validation hooks
    * Validation hooks are boolean predicates allowing or disallowing something to happen
    * [ ] Entering
    * [ ] Exiting
    * [ ] Any transition
    * [ ] Forced transition
    * [ ] Data change
    * [ ] Any action
* [x] Machine name
  * [x] definition name
    * [x] express definition in PEG #252 
  * [ ] instance name
  * [ ] involved in debug statements
  * [ ] involved in throws
  * [ ] factory pass-through
    * [ ] factory machine name factory method (lawl)
* [ ] Re-enable suppressed features
  * [ ] `load_state_machine/1`
  * [ ] `force_transition/1`
  * [ ] `valid_force_transition/1`
  * [ ] `is_changing/0`
* [ ] Available stochastic criteria
  * [ ] Minified lib responses are identical to source responses feature
  * [ ] When action required, action count + 1 >= node count
  * [ ] Stochastic networks' (.transition_count + 1) >= .node_count
  * [ ] Stochastic networks .transition_count >= .named_transition_count
  * [ ] Template string assembler matches application of template for every value
  * [ ] Rule order invariance.  Given any ordering of rules, `.equivalent(A,B)` still comes back true
* [ ] Other module stuff
  * [ ] Dive-style grep for module keyword auditing
  * [ ] Fluent API for module definitions
* [ ] Expose from GraphViz
  * [ ] dpi
  * [ ] fontname
  * [ ] fontcolor
  * [ ] fontsize
  * [ ] inputscale
  * [ ] landscape
  * [ ] margin
  * [ ] mindist
  * [ ] mode
  * [ ] model
  * [ ] newrank
  * [ ] nodesep
  * [ ] overlap
  * [ ] overlap_scaling
  * [ ] overlap_shrink
  * [ ] pack
  * [ ] packmode
  * [ ] pad
  * [ ] rankdir
  * [ ] ranksep
  * [ ] ratio
  * [ ] remincross
  * [ ] repulsiveforce
  * [ ] root
  * [ ] scale
  * [ ] sep
  * [ ] size
  * [ ] smoothing
  * [ ] splines
  * [ ] style
  * [ ] [target and url]
  * [ ] voro_margin
  * [ ] set truecolor=true
* [x] Layout #275
* [x] Probability #288
* [x] Better handling of color #297
* [x] Graph rendering of edges #298
* [x] Machine attributes #313 
* [x] Cleanup of old hypothetical PEG rules #319

**Comment by StoneCypher** [comment]
Add this to readme
<img width="500" alt="screen shot 2017-08-20 at 5 57 38 pm" src="https://user-images.githubusercontent.com/77482/29500010-2c762002-85d1-11e7-8a22-90cb98b4f53e.png">

**Comment by StoneCypher** [comment]
commuted to #329
