### ISSUE TITLE
Layout

### ISSUE THREAD

**Issue by StoneCypher** [StoneCypher/jssm#275]
* [x] Layout in DSL #272
* [x] Layout in compiler #273
* [x] Layout in API #274
