### ISSUE TITLE
Probability

### ISSUE THREAD

**Issue by StoneCypher** [StoneCypher/jssm#288]
* [x] Probabilities in data notation #285
* [x] Probabilities in DSL #286
* [x] probabilities in test sets #287
