### ISSUE TITLE
Modify atoms to be ready for sigils

### ISSUE THREAD

**Issue by StoneCypher** [StoneCypher/jssm#320]
* [x] Modify atoms to be ready for sigils
  * [x] Split atoms into first letter, rest of label #321
  * [x] Remove `&` from atoms' first letter definition #322
  * [x] Remove `@` from atoms' first letter definition #323
  * [x] Remove `#` from atoms' first letter definition #324
