### ISSUE TITLE
State declarations

### ISSUE THREAD

**Issue by StoneCypher** [StoneCypher/jssm#336]
* [x] Enforce name #330
* [x] Support feature lists #331
* [x] Explicitly enumerate features in feature list #340 
  * [x] Convert from feature list to properties #341 
* [x] Pass parser #332
* [x] Pass compiler #333
* [x] Consumed in constructor #338 
* [x] Reflected in API
* [x] Types #337
* [x] Tests #335

**Comment by machinshin** [comment]
@StoneCypher : looks like this can be closed?

**Comment by StoneCypher** [comment]
![image](https://user-images.githubusercontent.com/77482/71604348-454a6600-2b16-11ea-8230-b1f3aff1f66e.png)
