### ISSUE TITLE
Cycles

### ISSUE THREAD

**Issue by StoneCypher** [StoneCypher/jssm#346]
* [x] Cycles in parser #342
* [x] Cycles in compiler #343
* [ ] Conversion of cycle-relevant Flowtype #344
* [x] Test cases #345
* [ ] Transcompilation of cycles to transitions #347

**Comment by StoneCypher** [comment]
closed in favor of https://github.com/StoneCypher/fsl/issues/56
